spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 3030
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl